# Generated by Django 5.2.17 on 2026-10-02 00:26

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import dossiers.models.models_dossier
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('nom', models.CharField(help_text='Ex: Commune de Ngogom ou Campus UAD Bambey', max_length=255, verbose_name='Nom du dossier / territoire')),
                ('slug', models.SlugField(help_text='Généré automatiquement ou personnalisé pour les URLs contextuelles.', max_length=255, unique=True, verbose_name='Identifiant URL (Slug)')),
                ('description', models.TextField(blank=True, help_text='Précisions sur la mission territoriale, décrets ou mandats.', verbose_name='Description & Contexte administratif')),
                ('type_territoire', models.CharField(choices=[('commune', 'Collectivité Territoriale / Commune'), ('universite', 'Domaine Universitaire / Campus'), ('cadastre', 'Direction du Cadastre / Circonscription'), ('ministere', 'Périmètre Ministériel / Étatique'), ('autre', 'Autre Périmètre Territorial')], default='commune', max_length=50, verbose_name="Type d'entité territoriale")),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Polygone ou MultiPolygone englobant le territoire.', null=True, srid=4326, verbose_name='Emprise spatiale (EPSG:4326)')),
                ('srid_metrique', models.IntegerField(default=32628, help_text='Projection métrique de référence (ex: 32628 pour UTM 28N Sénégal).', verbose_name='SRID Métrique UTM')),
                ('centre_carte', django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Coordonnées initiales pour le centrage de la carte Leaflet.', null=True, srid=4326, verbose_name='Point central de cadrage')),
                ('zoom_defaut', models.PositiveSmallIntegerField(default=14, verbose_name='Niveau de zoom initial Leaflet')),
                ('superficie_ha', models.FloatField(default=0.0, help_text='Calculée automatiquement via transformation métrique UTM.', verbose_name='Superficie calculée (Hectares)')),
                ('modules_config', models.JSONField(blank=True, default=dossiers.models.models_dossier.get_default_modules_config, verbose_name='Configuration des modules métier activés')),
                ('role_gestionnaire_membres', models.CharField(default='admin', help_text="Rôle habilité par le Superuser pour assigner des membres à ce dossier (défaut: 'admin').", max_length=50, verbose_name='Rôle gestionnaire délégué')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour archiver un dossier sans supprimer ses données historiques.', verbose_name='Dossier actif')),
            ],
            options={
                'verbose_name': 'Dossier Territorial',
                'verbose_name_plural': 'Dossiers Territoriaux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DossierMembership',
            fields=[
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant UUID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur du Dossier'), ('operateur', 'Opérateur SIG / Technicien'), ('observateur', 'Observateur / Consultation')], default='observateur', max_length=50, verbose_name="Rôle dans l'espace de travail")),
                ('permissions_override', models.JSONField(blank=True, default=dict, help_text='Ajustements spécifiques de droits attribués à cet utilisateur sur ce dossier.', verbose_name='Surcharges de permissions locales')),
                ('assigned_by', models.ForeignKey(blank=True, help_text="Consigne le Superuser ou l'Admin délégué ayant accordé l'accès.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dossier_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Affecté par')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dossiers.dossier', verbose_name='Dossier de rattachement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dossier_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur affecté')),
            ],
            options={
                'verbose_name': 'Affectation à un Dossier',
                'verbose_name_plural': 'Affectations aux Dossiers',
                'ordering': ['-date_creation'],
                'unique_together': {('user', 'dossier')},
            },
        ),
    ]
