# Generated by Django 5.2.17 on 2026-10-02 13:06

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='dossiermembership',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.CreateModel(
            name='ReseauLineaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('nom', models.CharField(blank=True, help_text='Ex: Axe Principal Nord-Sud, Tronçon Ngogom-Bambey.', max_length=200, verbose_name='Nom / Tronçon')),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='Identifiant du tronçon')),
                ('type_voie', models.CharField(choices=[('route_bitumee', 'Route bitumée'), ('laterite', 'Route en latérite'), ('piste', 'Piste en terre'), ('allee_pietonne', 'Allée piétonne'), ('parking', 'Aire de stationnement / Parking'), ('canalisation', "Réseau d'assainissement / Canalisation"), ('autre', 'Autre tracé linéaire')], default='piste', max_length=40, verbose_name="Nature de l'infrastructure")),
                ('geometrie', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='Tracé cartographique (LineString WGS 84)')),
                ('longueur_metres', models.FloatField(blank=True, help_text='Calculée automatiquement en projection UTM.', null=True, verbose_name='Longueur métrique (m)')),
                ('largeur_estimee_m', models.FloatField(blank=True, null=True, verbose_name='Largeur approximative de la voie (m)')),
                ('etat_chaussee', models.CharField(blank=True, help_text='Bon, moyen, dégradé, impraticable en hivernage.', max_length=50, verbose_name='État de praticabilité')),
                ('description', models.TextField(blank=True, verbose_name='Observations')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseaux_lineaires', to='dossiers.dossier', verbose_name='Dossier territorial')),
            ],
            options={
                'verbose_name': 'Réseau linéaire & voirie',
                'verbose_name_plural': 'Réseaux linéaires & voiries',
                'ordering': ['dossier', 'type_voie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneSecteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(blank=True, help_text='Code technique unique (ex: V-001, SEC-01). Généré automatiquement si vide.', max_length=50, verbose_name='Identifiant de zone')),
                ('nom', models.CharField(help_text='Désignation toponymique usuelle.', max_length=200, verbose_name='Nom de la zone ou village')),
                ('type_zone', models.CharField(choices=[('village', 'Village'), ('quartier', 'Quartier urbain'), ('secteur_campus', "Secteur d'aménagement universitaire"), ('espace_libre', 'Espace libre / Réserve foncière'), ('espace_reserve', 'Espace réservé'), ('zone_agricole', 'Zone agricole / pastorale'), ('zone_activite', "Zone d'activités & équipements"), ('autre', 'Autre zonage')], default='village', max_length=50, verbose_name='Nature de la subdivision')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_etude', "En cours d'aménagement / étude"), ('archive', 'Archivé / Obsolète')], default='actif', max_length=30, verbose_name='Statut opérationnel')),
                ('description', models.TextField(blank=True, verbose_name='Description & Contexte')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Emprise spatiale (WGS 84)')),
                ('superficie_m2', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie (ha)')),
                ('population_estimee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population estimée')),
                ('responsable_nom', models.CharField(blank=True, max_length=150, verbose_name='Responsable / Chef de village')),
                ('responsable_telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone de contact')),
                ('metadata_specifique', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées spécifiques')),
                ('dossier', models.ForeignKey(help_text='Workspace territorial de rattachement.', on_delete=django.db.models.deletion.CASCADE, related_name='zones_secteurs', to='dossiers.dossier', verbose_name='Dossier territorial')),
            ],
            options={
                'verbose_name': 'Zone & Secteur territorial',
                'verbose_name_plural': 'Zones & Secteurs territoriaux',
                'ordering': ['dossier', 'nom'],
                'unique_together': {('dossier', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SignalementDommage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name="Numéro de dossier d'incident")),
                ('titre', models.CharField(max_length=150, verbose_name="Intitulé de l'incident")),
                ('categorie', models.CharField(choices=[('eau', 'Eau / Fuite'), ('electricite', 'Électricité / Câblage'), ('route', 'Voirie / Piste endommagée'), ('assainissement', 'Assainissement / Déchets'), ('eclairage', 'Éclairage public défaillant'), ('infrastructure', 'Bâtiment / Mur menaçant ruine'), ('foncier', 'Litige foncier / Empiètement illégal'), ('autre', 'Autre anomalie')], default='autre', max_length=30, verbose_name='Nature du dommage')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente / Péril imminent')], default='normale', max_length=20, verbose_name='Niveau de priorité')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau signalement'), ('pris_en_charge', "Pris en charge par l'équipe"), ('en_cours', 'Travaux / Intervention en cours'), ('resolu', 'Anomalie résolue'), ('rejete', 'Signalement non fondé / Rejeté')], default='nouveau', max_length=30, verbose_name="État d'avancement")),
                ('description', models.TextField(verbose_name='Description détaillée du problème')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name="Point GPS de l'incident")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='Photo de constatation')),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date et heure du signalement')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de clôture')),
                ('commentaire_resolution', models.TextField(blank=True, verbose_name="Rapport d'intervention ou motif de clôture")),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements_declares', to=settings.AUTH_USER_MODEL, verbose_name='Agent déclarant')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='dossiers.dossier', verbose_name='Dossier territorial')),
                ('zone_secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='dossiers.zonesecteur', verbose_name='Zone ou village concerné')),
            ],
            options={
                'verbose_name': 'Signalement de dommage',
                'verbose_name_plural': 'Signalements de dommages',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='UniteBatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(blank=True, help_text='Ex: BAT-001, M-0042. Généré automatiquement si vide.', max_length=50, verbose_name='Identifiant unique du bâti')),
                ('nom', models.CharField(blank=True, help_text='Ex: Amphithéâtre Diop, Concession Ndiaye.', max_length=200, verbose_name='Désignation / Nom usuel')),
                ('type_bati', models.CharField(choices=[('habitation', 'Habitation / Concession'), ('administratif', 'Bâtiment administratif'), ('pedagogique', 'Enseignement / Pédagogique'), ('sanitaire', 'Santé / Dispensaire'), ('commercial', 'Commerce / Marché'), ('culte', 'Lieu de culte'), ('sportif', 'Infrastructure sportive'), ('stockage', 'Entrepôt / Stockage'), ('autre', 'Autre édifice')], default='habitation', max_length=40, verbose_name='Usage principal du bâti')),
                ('statut_occupation', models.CharField(choices=[('habitee', 'Occupé / Habité'), ('non_habitee', 'Vacant / Non habité'), ('en_construction', 'En cours de construction'), ('ruine', 'Dégradé / En ruine')], default='habitee', max_length=30, verbose_name="Statut d'occupation")),
                ('etages', models.PositiveIntegerField(default=1, verbose_name='Nombre de niveaux (R+N)')),
                ('annee_construction', models.IntegerField(blank=True, null=True, verbose_name="Année d'édification")),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Emprise au sol (WGS 84)')),
                ('superficie_m2', models.FloatField(blank=True, null=True, verbose_name='Superficie au sol (m²)')),
                ('superficie_ha', models.FloatField(blank=True, null=True, verbose_name='Superficie au sol (ha)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='unites_baties/', verbose_name='Cliché terrain / drone')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Bâtiment existant et actif')),
                ('description', models.TextField(blank=True, verbose_name='Notes / Observations techniques')),
                ('metadata_specifique', models.JSONField(blank=True, default=dict, help_text='Structure murs, toiture, équipement solaire, raccordement eau, etc.', verbose_name='Attributs spécifiques du bâti')),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unites_baties', to='dossiers.dossier', verbose_name='Dossier territorial')),
                ('zone_secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unites_baties', to='dossiers.zonesecteur', verbose_name='Zone ou village de rattachement')),
            ],
            options={
                'verbose_name': 'Unité bâtie',
                'verbose_name_plural': 'Unités bâties',
                'ordering': ['dossier', 'code'],
                'unique_together': {('dossier', 'code')},
            },
        ),
    ]
