# Generated by Django 5.2.17 on 2026-10-04 05:04

import accounts.models.models_user
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='Action effectuée')),
                ('detail', models.TextField(blank=True, verbose_name='Détails contextuels')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': 'Journal des activités',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, help_text="Nomenclature standardisée [domaine]:[action] (ex: 'cadastre:view').", max_length=100, unique=True, verbose_name="Code d'habilitation")),
                ('nom', models.CharField(help_text="Intitulé compréhensible pour l'interface de gestion.", max_length=150, verbose_name='Libellé fonctionnel')),
                ('domaine', models.CharField(choices=[('dossier', 'Périmètres & Dossiers'), ('users', 'Comptes & Gouvernance'), ('audit', 'Audit & Sécurité'), ('cadastre', 'Cadastre & Espaces'), ('habitations', 'Habitations & Bâti'), ('signalements', 'Signalements & Dommages'), ('drones', 'Drones & Imagerie'), ('urbanisme', 'Urbanisme & PDU'), ('toponymie', 'Toponymie & POI'), ('settings', 'Configuration Système')], db_index=True, help_text='Module fonctionnel auquel est rattachée la permission.', max_length=50, verbose_name='Domaine métier')),
                ('description', models.TextField(blank=True, help_text='Explication détaillée de la portée et des prérogatives conférées.', verbose_name='Description & Portée')),
            ],
            options={
                'verbose_name': 'Permission RBAC',
                'verbose_name_plural': 'Permissions RBAC',
                'ordering': ['domaine', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, help_text="Code technique immuable (ex: 'admin', 'standard', 'technicien_sig').", max_length=50, unique=True, verbose_name='Identifiant unique du rôle')),
                ('nom', models.CharField(help_text="Libellé affiché dans les interfaces (ex: 'Administrateur Territorial').", max_length=100, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description du rôle')),
                ('is_canonical', models.BooleanField(default=False, help_text='Indique si ce rôle fait partie de la gouvernance socle (Superuser, Admin, Standard).', verbose_name='Rôle canonique système')),
            ],
            options={
                'verbose_name': 'Rôle RBAC',
                'verbose_name_plural': 'Rôles RBAC',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RolePermissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Liaison Rôle - Permission',
                'verbose_name_plural': 'Liaisons Rôles - Permissions',
            },
        ),
        migrations.CreateModel(
            name='UserPermissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('is_granted', models.BooleanField(default=True, help_text='True si la permission est explicitement accordée, False si explicitement révoquée.', verbose_name='Accordé')),
            ],
            options={
                'verbose_name': 'Dérogation Permission Utilisateur',
                'verbose_name_plural': 'Dérogations Permissions Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'Super Administrateur'), ('admin', 'Administrateur Territorial'), ('standard', 'Opérateur Standard'), ('domaine_foncier', 'Responsable Domaine Foncier (Legacy)'), ('administration', 'Administration Universitaire (Legacy)'), ('observateur', 'Observateur UAD (Legacy)'), ('maire', 'Responsable communal / Maire (Legacy)'), ('citoyen', 'Citoyen (Legacy)')], default='standard', help_text='Niveau hiérarchique principal (Superuser, Admin, Standard).', max_length=30, verbose_name='Rôle statutaire')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('acces_tous_territoires', models.BooleanField(default=False, help_text="Accorde l'accès automatique à l'ensemble des dossiers territoriaux (actuels et futurs).", verbose_name='Accès universel aux territoires')),
                ('must_change_password', models.BooleanField(default=False, help_text="Si activé, l'utilisateur doit obligatoirement définir un nouveau mot de passe lors de sa connexion.", verbose_name='Changement de mot de passe obligatoire')),
                ('created_by', models.ForeignKey(blank=True, help_text='Garantit la traçabilité de la chaîne de mandat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', accounts.models.models_user.CustomUserManager()),
            ],
        ),
    ]
