# Generated by Django 5.2.17 on 2026-10-04 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dossiers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Subdivision spatiale de rattachement (remplacé par les memberships de Dossier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitants', to='dossiers.zonesecteur', verbose_name='Zone ou village de référence'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Faisceau de permissions atomiques attribué à cet utilisateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='accounts.role', verbose_name='Profil RBAC associé'),
        ),
        migrations.AddField(
            model_name='rolepermissionlink',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='accounts.permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='rolepermissionlink',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='accounts.role', verbose_name='Rôle'),
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermissionLink', to='accounts.permission', verbose_name='Permissions associées'),
        ),
        migrations.AddField(
            model_name='userpermissionlink',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='accounts.permission', verbose_name='Permission'),
        ),
        migrations.AddField(
            model_name='userpermissionlink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permission_links', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions_custom',
            field=models.ManyToManyField(blank=True, related_name='custom_users', through='accounts.UserPermissionLink', to='accounts.permission', verbose_name='Surcharges individuelles de permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermissionlink',
            unique_together={('role', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='userpermissionlink',
            unique_together={('user', 'permission')},
        ),
    ]
