# Generated by Django 5.2.17 on 2026-10-02 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_village'),
        ('habitations', '0002_orthophotocommune'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, help_text="Nomenclature standardisée [domaine]:[action] (ex: 'cadastre:view').", max_length=100, unique=True, verbose_name="Code d'habilitation")),
                ('nom', models.CharField(help_text="Intitulé compréhensible pour l'interface de gestion.", max_length=150, verbose_name='Libellé fonctionnel')),
                ('domaine', models.CharField(choices=[('dossier', 'Périmètres & Dossiers'), ('users', 'Comptes & Gouvernance'), ('audit', 'Audit & Sécurité'), ('cadastre', 'Cadastre & Espaces'), ('habitations', 'Habitations & Bâti'), ('signalements', 'Signalements & Dommages'), ('drones', 'Drones & Imagerie'), ('urbanisme', 'Urbanisme & PDU'), ('toponymie', 'Toponymie & POI'), ('settings', 'Configuration Système')], db_index=True, help_text='Module fonctionnel auquel est rattachée la permission.', max_length=50, verbose_name='Domaine métier')),
                ('description', models.TextField(blank=True, help_text='Explication détaillée de la portée et des prérogatives conférées.', verbose_name='Description & Portée')),
            ],
            options={
                'verbose_name': 'Permission RBAC',
                'verbose_name_plural': 'Permissions RBAC',
                'ordering': ['domaine', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('code', models.CharField(db_index=True, help_text="Code technique immuable (ex: 'admin', 'standard', 'technicien_sig').", max_length=50, unique=True, verbose_name='Identifiant unique du rôle')),
                ('nom', models.CharField(help_text="Libellé affiché dans les interfaces (ex: 'Administrateur Territorial').", max_length=100, verbose_name='Nom du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description du rôle')),
                ('is_canonical', models.BooleanField(default=False, help_text='Indique si ce rôle fait partie de la gouvernance socle (Superuser, Admin, Standard).', verbose_name='Rôle canonique système')),
            ],
            options={
                'verbose_name': 'Rôle RBAC',
                'verbose_name_plural': 'Rôles RBAC',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Garantit la traçabilité de la chaîne de mandat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(max_length=200, verbose_name='Action effectuée'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='detail',
            field=models.TextField(blank=True, verbose_name='Détails contextuels'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superuser', 'Super Administrateur'), ('admin', 'Administrateur Territorial'), ('standard', 'Opérateur Standard'), ('domaine_foncier', 'Responsable Domaine Foncier (Legacy)'), ('administration', 'Administration Universitaire (Legacy)'), ('observateur', 'Observateur UAD (Legacy)'), ('maire', 'Responsable communal / Maire (Legacy)'), ('citoyen', 'Citoyen (Legacy)')], default='standard', help_text='Niveau hiérarchique principal (Superuser, Admin, Standard).', max_length=30, verbose_name='Rôle statutaire'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Champ historique déprécié (remplacé par les memberships de Dossier).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitants', to='habitations.village', verbose_name='Village de référence'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='assigned_role',
            field=models.ForeignKey(blank=True, help_text='Faisceau de permissions atomiques attribué à cet utilisateur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='accounts.role', verbose_name='Profil RBAC associé'),
        ),
        migrations.CreateModel(
            name='RolePermissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='accounts.permission', verbose_name='Permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_links', to='accounts.role', verbose_name='Rôle')),
            ],
            options={
                'verbose_name': 'Liaison Rôle - Permission',
                'verbose_name_plural': 'Liaisons Rôles - Permissions',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermissionLink', to='accounts.permission', verbose_name='Permissions associées'),
        ),
        migrations.CreateModel(
            name='UserPermissionLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('is_granted', models.BooleanField(default=True, help_text='True si la permission est explicitement accordée, False si explicitement révoquée.', verbose_name='Accordé')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_links', to='accounts.permission', verbose_name='Permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permission_links', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dérogation Permission Utilisateur',
                'verbose_name_plural': 'Dérogations Permissions Utilisateurs',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions_custom',
            field=models.ManyToManyField(blank=True, related_name='custom_users', through='accounts.UserPermissionLink', to='accounts.permission', verbose_name='Surcharges individuelles de permissions'),
        ),
    ]
