# Generated by Django 5.2.17 on 2026-10-02 13:06

import accounts.models.models_user
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_permission_role_customuser_created_by_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.models_user.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='permission',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='role',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='rolepermissionlink',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userpermissionlink',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
    ]
