# Generated by Django 5.2.17 on 2026-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='acces_tous_territoires',
            field=models.BooleanField(
                default=False,
                help_text="Accorde l'accès automatique à l'ensemble des dossiers territoriaux (actuels et futurs).",
                verbose_name='Accès universel aux territoires'
            ),
        ),
    ]
