# Generated by Django 5.2.15 on 2026-09-29 16:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commune', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrthophotoCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('source', models.URLField(blank=True, max_length=500, verbose_name='Source (lien WebODM)')),
                ('fichier', models.CharField(blank=True, max_length=500, verbose_name='GeoTIFF (chemin dans MEDIA)')),
                ('tiles_url', models.CharField(max_length=500, verbose_name='URL des tuiles XYZ')),
                ('zoom_min', models.PositiveSmallIntegerField(default=14)),
                ('zoom_max', models.PositiveSmallIntegerField(default=21)),
                ('resolution', models.FloatField(blank=True, null=True, verbose_name='Résolution (cm/pixel)')),
                ('emprise', django.contrib.gis.db.models.fields.MultiPolygonField(help_text="Contour réel des zones survolées (une partie par zone), calculé depuis l'image.", srid=4326, verbose_name='Zones couvertes')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie couverte (m²)')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orthophoto communale',
                'verbose_name_plural': 'Orthophotos communales',
                'ordering': ['-date_ajout'],
            },
        ),
    ]
