# Generated by Django 5.2.15 on 2026-07-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0007_espacevert_pointinteret_terrain_voirie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voirie',
            name='type_voirie',
            field=models.CharField(blank=True, choices=[('principale', 'Voie principale'), ('secondaire', 'Voie secondaire'), ('pietonne', 'Allée piétonne'), ('parking', 'Parking')], max_length=20, verbose_name='Type'),
        ),
    ]
