# Generated by Django 5.2.15 on 2026-09-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_merge_roles_observateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('domaine_foncier', 'Responsable Domaine Foncier'), ('administration', 'Administration Universitaire'), ('observateur', 'Observateur UAD'), ('maire', 'Responsable communal / Maire'), ('citoyen', 'Citoyen')], default='observateur', max_length=20),
        ),
    ]
