# Generated by Django 5.2.15 on 2026-06-11 15:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territoire', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_travaux', models.CharField(choices=[('construction', 'Construction'), ('renovation', 'Rénovation'), ('extension', 'Extension'), ('demolition', 'Démolition')], max_length=20, verbose_name='Type de travaux')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('description', models.TextField(verbose_name='Description')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Coût estimé (FCFA)')),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200, verbose_name="Maître d'ouvrage")),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('batiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='territoire.batiment', verbose_name='Bâtiment')),
            ],
            options={
                'verbose_name': 'Historique de Construction',
                'verbose_name_plural': 'Historique des Constructions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='NouvelleConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_projet', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('type_construction', models.CharField(max_length=200, verbose_name='Type de construction')),
                ('superficie_souhaitee', models.FloatField(verbose_name='Superficie souhaitée (m²)')),
                ('zone_souhaitee', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Zone souhaitée')),
                ('disponible', models.BooleanField(blank=True, null=True, verbose_name='Zone disponible')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('en_cours', 'En cours'), ('terminee', 'Terminée')], default='attente', max_length=20)),
                ('rapport_faisabilite', models.TextField(blank=True, verbose_name='Rapport de faisabilité')),
                ('zones_alternatives', models.TextField(blank=True, verbose_name='Zones alternatives proposées')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
            ],
            options={
                'verbose_name': 'Nouvelle Construction',
                'verbose_name_plural': 'Nouvelles Constructions',
                'ordering': ['-date_demande'],
            },
        ),
    ]
