# Generated by Django 5.2.17 on 2026-10-04 05:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('type_travaux', models.CharField(choices=[('construction', 'Construction neuve'), ('renovation', 'Rénovation / Réhabilitation'), ('extension', 'Extension / Agrandissement'), ('demolition', 'Démolition / Déconstruction')], max_length=20, verbose_name='Nature des travaux')),
                ('date_debut', models.DateField(verbose_name='Date de démarrage')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name="Date d'achèvement")),
                ('description', models.TextField(verbose_name='Descriptif des travaux')),
                ('cout', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Coût engagé (FCFA)')),
                ('maitre_ouvrage', models.CharField(blank=True, max_length=200, verbose_name="Maître d'ouvrage / Prestataire")),
                ('unite_batie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historiques_travaux', to='dossiers.unitebatie', verbose_name='Unité bâtie')),
            ],
            options={
                'verbose_name': 'Historique de Construction',
                'verbose_name_plural': 'Historiques de Constructions',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='NouvelleConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification')),
                ('nom_projet', models.CharField(max_length=200, verbose_name='Nom du projet')),
                ('type_construction', models.CharField(max_length=200, verbose_name='Type de construction')),
                ('superficie_souhaitee', models.FloatField(verbose_name='Superficie souhaitée (m²)')),
                ('zone_souhaitee', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Zone souhaitée')),
                ('disponible', models.BooleanField(blank=True, null=True, verbose_name='Zone disponible')),
                ('statut', models.CharField(choices=[('en_cours', "En cours d'instruction"), ('approuvee', 'Approuvée / Autorisée'), ('rejetee', 'Rejetée')], default='en_cours', max_length=20, verbose_name='Statut')),
                ('rapport_faisabilite', models.TextField(blank=True, verbose_name='Rapport de faisabilité')),
                ('zones_alternatives', models.TextField(blank=True, verbose_name='Zones alternatives proposées')),
                ('date_demande', models.DateTimeField(auto_now_add=True, verbose_name='Date de demande')),
                ('demandeur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_construction', to='dossiers.dossier', verbose_name='Dossier territorial')),
                ('zone_secteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_construction', to='dossiers.zonesecteur', verbose_name='Zone ou secteur ciblé')),
            ],
            options={
                'verbose_name': 'Nouvelle Construction',
                'verbose_name_plural': 'Nouvelles Constructions',
                'ordering': ['-date_demande'],
            },
        ),
    ]
