# Generated by Django 5.2.15 on 2026-06-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urbanisme', '0001_initial'),
        ('territoire', '0004_add_taux_occupation_espace'),
    ]

    operations = [
        migrations.AddField(
            model_name='nouvelleconstruction',
            name='espace_souhaitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='constructions_demandees', to='territoire.espace', verbose_name='Espace sélectionné'),
        ),
    ]
