# Generated by Django 5.2.17 on 2026-10-02 13:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_alter_dossier_date_creation_and_more'),
        ('territoire', '0011_migrer_espace_en_campus'),
        ('urbanisme', '0003_simplifier_statuts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiqueconstruction',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Historique de Construction', 'verbose_name_plural': 'Historiques de Constructions'},
        ),
        migrations.RemoveField(
            model_name='historiqueconstruction',
            name='date_ajout',
        ),
        migrations.AddField(
            model_name='historiqueconstruction',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='historiqueconstruction',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification'),
        ),
        migrations.AddField(
            model_name='historiqueconstruction',
            name='unite_batie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_travaux', to='dossiers.unitebatie', verbose_name='Unité bâtie (V2)'),
        ),
        migrations.AddField(
            model_name='nouvelleconstruction',
            name='date_creation',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Enregistré automatiquement lors de la création de la fiche.', verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='nouvelleconstruction',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projets_construction', to='dossiers.dossier', verbose_name='Dossier territorial'),
        ),
        migrations.AddField(
            model_name='nouvelleconstruction',
            name='zone_secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_construction', to='dossiers.zonesecteur', verbose_name='Zone ou secteur ciblé'),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='batiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='territoire.batiment', verbose_name='Bâtiment (Campus)'),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='cout',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Coût engagé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='date_debut',
            field=models.DateField(verbose_name='Date de démarrage'),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'achèvement"),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='description',
            field=models.TextField(verbose_name='Descriptif des travaux'),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='maitre_ouvrage',
            field=models.CharField(blank=True, max_length=200, verbose_name="Maître d'ouvrage / Prestataire"),
        ),
        migrations.AlterField(
            model_name='historiqueconstruction',
            name='type_travaux',
            field=models.CharField(choices=[('construction', 'Construction neuve'), ('renovation', 'Rénovation / Réhabilitation'), ('extension', 'Extension / Agrandissement'), ('demolition', 'Démolition / Déconstruction')], max_length=20, verbose_name='Nature des travaux'),
        ),
        migrations.AlterField(
            model_name='nouvelleconstruction',
            name='date_demande',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de demande'),
        ),
        migrations.AlterField(
            model_name='nouvelleconstruction',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, help_text='Mis à jour automatiquement lors de toute modification.', verbose_name='Dernière modification'),
        ),
        migrations.AlterField(
            model_name='nouvelleconstruction',
            name='statut',
            field=models.CharField(choices=[('en_cours', "En cours d'instruction"), ('approuvee', 'Approuvée / Autorisée'), ('rejetee', 'Rejetée')], default='en_cours', max_length=20, verbose_name='Statut'),
        ),
    ]
