# Generated by Django 5.2.15 on 2026-06-11 15:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la mission')),
                ('date_mission', models.DateField(verbose_name='Date de la mission')),
                ('operateur', models.CharField(max_length=200, verbose_name='Opérateur')),
                ('drone_utilise', models.CharField(blank=True, max_length=100, verbose_name='Drone utilisé')),
                ('zone_couverte', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Zone couverte')),
                ('altitude_vol', models.FloatField(blank=True, null=True, verbose_name='Altitude (m)')),
                ('recouvrement', models.FloatField(blank=True, null=True, verbose_name='Taux de recouvrement (%)')),
                ('statut', models.CharField(choices=[('planifie', 'Planifiée'), ('realise', 'Réalisée'), ('traite', 'Traitée')], default='planifie', max_length=20)),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mission Drone',
                'verbose_name_plural': 'Missions Drones',
                'ordering': ['-date_mission'],
            },
        ),
        migrations.CreateModel(
            name='Orthophoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fichier', models.ImageField(upload_to='orthophotos/', verbose_name='Fichier image')),
                ('date_prise', models.DateField(verbose_name='Date de prise de vue')),
                ('resolution', models.FloatField(blank=True, null=True, verbose_name='Résolution (cm/px)')),
                ('emprise', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Emprise géographique')),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthophotos', to='drones.missiondrone', verbose_name='Mission')),
            ],
            options={
                'verbose_name': 'Orthophoto',
                'verbose_name_plural': 'Orthophotos',
                'ordering': ['-date_prise'],
            },
        ),
    ]
