# Generated by Django 5.2.15 on 2026-07-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0008_rattache_orthophotos_existantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='orthophoto',
            name='tuiles_locales',
            field=models.BooleanField(default=False, help_text='Si activé, tiles_url pointe vers des tuiles stockées sur ce serveur (indépendantes de WebODM) plutôt que vers WebODM directement.', verbose_name='Tuiles générées localement'),
        ),
    ]
