# Generated by Django 5.2.17 on 2026-10-04 05:04

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dossiers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fichier', models.FileField(upload_to='flux_videos/', verbose_name='Fichier vidéo')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('duree_secondes', models.IntegerField(blank=True, null=True, verbose_name='Durée (s)')),
                ('taille_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('operateur', models.CharField(blank=True, max_length=100, verbose_name='Opérateur')),
                ('source_rtsp', models.CharField(blank=True, max_length=500, verbose_name='Source RTSP')),
            ],
            options={
                'verbose_name': 'Flux vidéo',
                'verbose_name_plural': 'Flux vidéos',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la mission')),
                ('date_vol', models.DateField(verbose_name='Date du vol')),
                ('operateur', models.CharField(blank=True, max_length=200, verbose_name='Opérateur')),
                ('drone_utilise', models.CharField(blank=True, max_length=200, verbose_name='Drone utilisé')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude de vol (m)')),
                ('duree_minutes', models.FloatField(blank=True, null=True, verbose_name='Durée du vol (min)')),
                ('superficie_prevue', models.FloatField(blank=True, null=True, verbose_name='Superficie prévue (ha)')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('traitement', 'En traitement'), ('traitee', 'Traitée'), ('integree', 'Intégrée')], default='attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions_drone', to='dossiers.dossier', verbose_name='Dossier territorial')),
            ],
            options={
                'verbose_name': 'Mission drone',
                'verbose_name_plural': 'Missions drone',
                'ordering': ['-date_vol'],
            },
        ),
        migrations.CreateModel(
            name='Orthophoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fichier', models.FileField(upload_to='orthophotos/', verbose_name='Fichier (GeoTIFF, PNG, JPEG)')),
                ('date_prise', models.DateField(verbose_name='Date de prise de vue')),
                ('operateur', models.CharField(blank=True, max_length=200, verbose_name='Opérateur')),
                ('resolution', models.FloatField(blank=True, null=True, verbose_name='Résolution (cm/px)')),
                ('emprise', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Emprise géographique')),
                ('systeme_proj', models.CharField(blank=True, max_length=200, verbose_name='Système de projection')),
                ('largeur_px', models.IntegerField(blank=True, null=True, verbose_name='Largeur (px)')),
                ('hauteur_px', models.IntegerField(blank=True, null=True, verbose_name='Hauteur (px)')),
                ('tiles_url', models.CharField(blank=True, help_text='Format : /static/tiles/{z}/{x}/{y}.png ou URL WebODM', max_length=500, verbose_name='URL tuiles XYZ (WebODM)')),
                ('tuiles_locales', models.BooleanField(default=False, help_text='Si activé, tiles_url pointe vers des tuiles stockées sur ce serveur (indépendantes de WebODM) plutôt que vers WebODM directement.', verbose_name='Tuiles générées localement')),
                ('description', models.TextField(blank=True)),
                ('valide', models.BooleanField(default=False, verbose_name='Validée')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthophotos', to='dossiers.dossier', verbose_name='Dossier territorial')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthophotos', to='drones.mission', verbose_name='Mission associée')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthophotos_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Orthophoto',
                'verbose_name_plural': 'Orthophotos',
                'ordering': ['-date_prise'],
            },
        ),
        migrations.CreateModel(
            name='PhotoDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('image', models.ImageField(upload_to='photos_drone/', verbose_name='Image')),
                ('date_capture', models.DateTimeField(auto_now_add=True, verbose_name='Date de capture')),
                ('operateur', models.CharField(blank=True, max_length=100, verbose_name='Opérateur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='drones.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'Photo drone',
                'verbose_name_plural': 'Photos drone',
                'ordering': ['-date_capture'],
            },
        ),
    ]
