# Generated by Django 5.2.17 on 2026-10-05 13:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='emprise',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Zone de vol (Emprise autorisée)'),
        ),
        migrations.AddField(
            model_name='mission',
            name='trajectoire',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Trajectoire de vol planifiée'),
        ),
    ]
