# Generated by Django 5.2.15 on 2026-06-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0005_ajoute_fluxvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoDrone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('image', models.ImageField(upload_to='photos_drone/', verbose_name='Image')),
                ('date_capture', models.DateTimeField(auto_now_add=True, verbose_name='Date de capture')),
                ('operateur', models.CharField(blank=True, max_length=100, verbose_name='Opérateur')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Photo drone',
                'verbose_name_plural': 'Photos drone',
                'ordering': ['-date_capture'],
            },
        ),
    ]
