# Generated by Django 5.2.15 on 2026-07-06 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0006_ajoute_photodrone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la mission')),
                ('date_vol', models.DateField(verbose_name='Date du vol')),
                ('operateur', models.CharField(blank=True, max_length=200, verbose_name='Opérateur')),
                ('drone_utilise', models.CharField(blank=True, max_length=200, verbose_name='Drone utilisé')),
                ('altitude', models.FloatField(blank=True, null=True, verbose_name='Altitude de vol (m)')),
                ('duree_minutes', models.FloatField(blank=True, null=True, verbose_name='Durée du vol (min)')),
                ('superficie_prevue', models.FloatField(blank=True, null=True, verbose_name='Superficie prévue (ha)')),
                ('statut', models.CharField(choices=[('attente', 'En attente'), ('traitement', 'En traitement'), ('traitee', 'Traitée'), ('integree', 'Intégrée')], default='attente', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mission drone',
                'verbose_name_plural': 'Missions drone',
                'ordering': ['-date_vol'],
            },
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de validation'),
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthophotos_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par'),
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='valide',
            field=models.BooleanField(default=False, verbose_name='Validée'),
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orthophotos', to='drones.mission', verbose_name='Mission associée'),
        ),
        migrations.AddField(
            model_name='photodrone',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='drones.mission', verbose_name='Mission associée'),
        ),
    ]
