# Generated by Django 5.2.17 on 2026-10-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dossiers', '0002_alter_dossier_date_creation_and_more'),
        ('drones', '0009_orthophoto_tuiles_locales'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='missions_drone', to='dossiers.dossier', verbose_name='Dossier territorial'),
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='dossier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orthophotos', to='dossiers.dossier', verbose_name='Dossier territorial'),
        ),
    ]
