# Generated by Django 5.2.15 on 2026-06-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0004_add_taux_occupation_espace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batiment',
            name='capacite',
        ),
    ]
