# Generated by Django 5.2.15 on 2026-07-14 00:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0006_suivitravaux'),
    ]

    operations = [
        migrations.CreateModel(
            name='EspaceVert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_espace_vert', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('etat', models.CharField(blank=True, max_length=100, verbose_name='État')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espace vert',
                'verbose_name_plural': 'Espaces verts',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PointInteret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('categorie', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Géométrie')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Point d'intérêt",
                'verbose_name_plural': "Points d'intérêt",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_terrain', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('etat', models.CharField(blank=True, max_length=100, verbose_name='État')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Voirie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('type_voirie', models.CharField(blank=True, max_length=100, verbose_name='Type')),
                ('revetement', models.CharField(blank=True, max_length=100, verbose_name='Revêtement')),
                ('etat', models.CharField(blank=True, max_length=100, verbose_name='État')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='Géométrie')),
                ('longueur', models.FloatField(blank=True, null=True, verbose_name='Longueur (m)')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voirie',
                'verbose_name_plural': 'Voiries',
                'ordering': ['nom'],
            },
        ),
    ]
