# Generated by Django 5.2.15 on 2026-07-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foncier', '0008_alter_voirie_type_voirie'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacevert',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='espacevert',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='espacevert',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='espacevert',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='espaces_verts/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='terrain',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='terrains/', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='voirie',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='voirie',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='voirie',
            name='est_actif',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='voirie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='voiries/', verbose_name='Photo'),
        ),
    ]
