# Generated by Django 5.2.15 on 2026-06-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0003_drone_orthophoto_geotiff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orthophoto',
            name='mission',
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='operateur',
            field=models.CharField(blank=True, max_length=200, verbose_name='Opérateur'),
        ),
        migrations.AddField(
            model_name='orthophoto',
            name='tiles_url',
            field=models.CharField(blank=True, help_text='Format : /static/tiles/{z}/{x}/{y}.png ou URL WebODM', max_length=500, verbose_name='URL tuiles XYZ (WebODM)'),
        ),
        migrations.DeleteModel(
            name='MissionDrone',
        ),
    ]
