# Generated by Django 5.2.15 on 2026-06-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drones', '0004_supprime_missiondrone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluxVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('fichier', models.FileField(upload_to='flux_videos/', verbose_name='Fichier vidéo')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('duree_secondes', models.IntegerField(blank=True, null=True, verbose_name='Durée (s)')),
                ('taille_octets', models.BigIntegerField(blank=True, null=True, verbose_name='Taille (octets)')),
                ('operateur', models.CharField(blank=True, max_length=100, verbose_name='Opérateur')),
                ('source_rtsp', models.CharField(blank=True, max_length=500, verbose_name='Source RTSP')),
            ],
            options={
                'verbose_name': 'Flux vidéo',
                'verbose_name_plural': 'Flux vidéos',
                'ordering': ['-date_enregistrement'],
            },
        ),
    ]
