# Generated by Django 5.2.15 on 2026-09-29 15:59

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Ngogom', max_length=150, verbose_name='Nom')),
                ('departement', models.CharField(default='Bambey', max_length=100, verbose_name='Département')),
                ('region', models.CharField(default='Diourbel', max_length=100, verbose_name='Région')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
            },
        ),
        migrations.CreateModel(
            name='Piste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=150, verbose_name='Nom / tronçon')),
                ('type_voie', models.CharField(choices=[('route', 'Route bitumée'), ('laterite', 'Route en latérite'), ('piste', 'Piste')], default='piste', max_length=20, verbose_name='Type')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326, verbose_name='Tracé')),
                ('longueur', models.FloatField(blank=True, null=True, verbose_name='Longueur (m)')),
            ],
            options={
                'verbose_name': 'Route / piste',
                'verbose_name_plural': 'Routes et pistes',
                'ordering': ['type_voie', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('eau', 'Eau'), ('electricite', 'Électricité'), ('route', 'Route / piste'), ('assainissement', 'Assainissement'), ('eclairage', 'Éclairage public'), ('infrastructure', 'Infrastructure'), ('autre', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('titre', models.CharField(help_text="Ex : Tuyau d'eau cassé", max_length=120, verbose_name='Problème en quelques mots')),
                ('description', models.TextField(verbose_name='Description')),
                ('date_signalement', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du signalement')),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='normale', max_length=10, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('pris_en_charge', 'Pris en charge'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('geometrie', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='Localisation')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='signalements/', verbose_name='Photo (optionnelle)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to=settings.AUTH_USER_MODEL, verbose_name='Signalé par')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'ordering': ['-date_signalement'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_commune', to=settings.AUTH_USER_MODEL)),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='habitations.signalement')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSignalement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_statut', models.CharField(blank=True, choices=[('nouveau', 'Nouveau'), ('pris_en_charge', 'Pris en charge'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], max_length=20, verbose_name='Ancien statut')),
                ('nouveau_statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('pris_en_charge', 'Pris en charge'), ('en_cours', 'En cours'), ('resolu', 'Résolu')], max_length=20, verbose_name='Nouveau statut')),
                ('date_changement', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('commentaire', models.CharField(blank=True, max_length=255, verbose_name='Commentaire')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Par')),
                ('signalement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='habitations.signalement', verbose_name='Signalement')),
            ],
            options={
                'verbose_name': 'Historique de signalement',
                'verbose_name_plural': 'Historique des signalements',
                'ordering': ['date_changement'],
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Laissez vide pour une numérotation automatique (V-001, V-002…).', max_length=30, unique=True, verbose_name='Identifiant')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom du village')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='habitations.commune', verbose_name='Commune')),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='signalement',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Détecté automatiquement à partir de la position si vous le laissez vide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signalements', to='habitations.village', verbose_name='Village concerné'),
        ),
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Laissez vide pour une numérotation automatique (M-0001, M-0002…).', max_length=30, unique=True, verbose_name='Identifiant')),
                ('statut_occupation', models.CharField(choices=[('habitee', 'Habitée'), ('non_habitee', 'Non habitée')], default='habitee', max_length=20, verbose_name="Statut d'occupation")),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maisons', to='habitations.village', verbose_name='Village')),
            ],
            options={
                'verbose_name': 'Maison',
                'verbose_name_plural': 'Maisons',
                'ordering': ['code'],
            },
        ),
    ]
