# Generated by Django 5.2.15 on 2026-06-11 15:15

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Espace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('type_espace', models.CharField(choices=[('libre', 'Espace libre'), ('occupe', 'Espace occupé'), ('reserve', 'Espace réservé'), ('route', 'Route / Voie'), ('vert', 'Espace vert'), ('sportif', 'Espace sportif')], max_length=20, verbose_name='Type')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('usage', models.CharField(blank=True, max_length=200, verbose_name='Usage')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Espace',
                'verbose_name_plural': 'Espaces',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FonctionBatiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Fonction de bâtiment',
                'verbose_name_plural': 'Fonctions de bâtiments',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Batiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('etages', models.PositiveIntegerField(default=1, verbose_name="Nombre d'étages")),
                ('annee_construction', models.IntegerField(blank=True, null=True, verbose_name='Année de construction')),
                ('capacite', models.IntegerField(blank=True, null=True, verbose_name='Capacité (personnes)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='batiments/', verbose_name='Photo')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('fonction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='territoire.fonctionbatiment', verbose_name='Fonction')),
            ],
            options={
                'verbose_name': 'Bâtiment',
                'verbose_name_plural': 'Bâtiments',
                'ordering': ['nom'],
            },
        ),
    ]
