# Generated by Django 5.2.15 on 2026-06-17 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territoire', '0003_fonctions_batiment_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='espace',
            name='taux_occupation',
            field=models.FloatField(default=60.0, help_text='Pourcentage de la superficie effectivement constructible (le reste est réservé aux voiries, espaces verts, parkings…)', validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)], verbose_name="Taux d'occupation max (%)"),
        ),
    ]
