# Generated by Django 5.2.15 on 2026-07-15 21:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territoire', '0009_espacevert_code_espacevert_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Campus UAD Bambey', max_length=200, verbose_name='Nom')),
                ('geometrie', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Géométrie')),
                ('superficie', models.FloatField(blank=True, null=True, verbose_name='Superficie (m²)')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campus',
                'verbose_name_plural': 'Campus',
            },
        ),
        migrations.AddField(
            model_name='espace',
            name='campus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_espaces', to='territoire.campus', verbose_name='Campus'),
        ),
    ]
